#!/usr/bin/env python3
"""扫描 step4-assets 目录，生成 gallery_data.js 供 gallery.html 加载。

用法：
    python3 update_gallery.py

生成图片后刷新 gallery.html 即可看到最新资产。
"""
import json, os

CATS = ["characters", "locations", "props"]
IMG_EXT = {".png", ".jpg", ".jpeg", ".webp"}
BASE = os.path.dirname(os.path.abspath(__file__))

assets = []
for cat in CATS:
    cat_dir = os.path.join(BASE, cat)
    if not os.path.isdir(cat_dir):
        continue
    for name in sorted(os.listdir(cat_dir)):
        item_dir = os.path.join(cat_dir, name)
        if not os.path.isdir(item_dir):
            continue
        stages, images = [], []
        for sub in sorted(os.listdir(item_dir)):
            sub_path = os.path.join(item_dir, sub)
            if not os.path.isdir(sub_path):
                continue
            if sub == "_portrait":
                for f in sorted(os.listdir(sub_path)):
                    if os.path.splitext(f)[1].lower() in IMG_EXT:
                        images.append({"path": f"{cat}/{name}/_portrait/{f}",
                                       "label": f"肖像 · {os.path.splitext(f)[0]}"})
            else:
                stages.append(sub)
                for f in sorted(os.listdir(sub_path)):
                    if os.path.splitext(f)[1].lower() in IMG_EXT:
                        images.append({"path": f"{cat}/{name}/{sub}/{f}",
                                       "label": f"{sub} · {os.path.splitext(f)[0]}"})
        assets.append({"category": cat, "name": name, "stages": stages, "images": images})

out_path = os.path.join(BASE, "gallery_data.js")
with open(out_path, "w", encoding="utf-8") as f:
    f.write("// Auto-generated by update_gallery.py — do not edit manually\n")
    f.write(f"const ASSET_DATA = {json.dumps(assets, ensure_ascii=False)};\n")

img_total = sum(len(a["images"]) for a in assets)
print(f"✅ gallery_data.js 已更新: {len(assets)} 个资产, {img_total} 张图片")
